# Generated by Django 4.1.7 on 2023-03-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
                ('gre', models.IntegerField()),
                ('toefl', models.IntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
